### ISSUE TITLE
Compiler error when trying to derive PyOp on a DAT

### ISSUE THREAD

**Issue by rosofo** [tychedelia/td-rs#8]
See: https://github.com/rosofo/td-rs/commit/d09a17335f6f8a9f70b0b6ffd69d9621c68a6e31#diff-6f3d6d0a992f7bc61944825d65c52bd7b0eaf00feea520ebcd328dd8bb6cb660R21-R25 for a reproduction

Getting the following error after copying the `filter-dat` example and then trying to add Python:

```
error[E0119]: conflicting implementations of trait `td_rs_dat::PyGetSets` for type `FilterDat`
  --> plugins/dat/tdtidal/src/lib.rs:22:10
   |
22 | #[derive(PyOp, Debug)]
   |          ^^^^
   |
   = note: conflicting implementation in crate `td_rs_base`:
           - impl<T> td_rs_dat::PyGetSets for T;
   = note: this error originates in the derive macro `PyOp` (in Nightly builds, run with -Z macro-backtrace for more info)
```

with `RUSTFLAGS="-Z macro-backtrace"`:

```
error[E0405]: cannot find trait `PyGetSets` in this scope
  --> plugins/dat/tdtidal/src/lib.rs:22:10
   |
22 | #[derive(PyOp, Debug)]
   |          ^^^^
   |          |
   |          not found in this scope
   |          in this derive macro expansion
   |
  ::: /Users/robinforbes/code/td-rs/td-rs-derive-py/src/lib.rs:9:1
   |
9  | pub fn params_derive(input: TokenStream) -> TokenStream {
   | ------------------------------------------------------- in this expansion of `#[derive(PyOp)]`
```

**Comment by rosofo** [comment]
Interestingly the first error is reported by RLS, the second on the command-line.

**Comment by rosofo** [comment]
Also I just realised I didn't include the python feature with `td-rs-dat = { path = "../../../td-rs-dat", features = ["python"] }`, but adding it makes no difference

**Comment by tychedelia** [comment]
Just a heads up, I'm currently reworking this to use `pyo3` directly instead of our own custom derive macro (which is hacky and easy to break): https://discord.com/channels/510576398109245510/510579102151868460/1302173732973838437

**Comment by rosofo** [comment]
Sounds good!
